In [1]:
import pandas as pd
import numpy as np
import pickle as pkl
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPool2D

from sklearn.neighbors import NearestNeighbors
import os
from numpy.linalg import norm

In [2]:
filenames=[]
for file in os.listdir('images'):
    filenames.append(os.path.join('images',file))

In [3]:
len(filenames)

44441

In [4]:
model=ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
model.trainable=False
model=tf.keras.Sequential([model, GlobalMaxPool2D()])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ resnet50 (Functional)                │ (None, 7, 7, 2048)          │      23,587,712 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling2d                 │ (None, 2048)                │               0 │
│ (GlobalMaxPooling2D)                 │                             │                 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 23,587,712 (89.98 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 23,587,712 (89.98 MB)

In [5]:
img=image.load_img('images/16871.jpg',target_size=(224,224))

In [6]:
def extract_features_from_images(image_path,model):
    img=image.load_img(image_path, target_size=(224,224))
    img_array=image.img_to_array(img)
    img_expand_dim=np.expand_dims(img_array,axis=0)
    # img_expand_dim.shape
    img_preprocess=preprocess_input(img_expand_dim)
    # img_preprocess.shape
    result=model.predict(img_preprocess).flatten()
    # result.shape
    norm_result=result/norm(result)
    return norm_result

In [7]:
extract_features_from_images(filenames[0],model)

1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step


array([0.        , 0.01761625, 0.00171601, ..., 0.01247231, 0.02726393,
       0.06899248], dtype=float32)

In [8]:
image_features=[]
for file in filenames[0:1000]:
    image_features.append(extract_features_from_images(file,model))
    # break
image_features

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 199ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 

[array([0.        , 0.01761625, 0.00171601, ..., 0.01247231, 0.02726393,
        0.06899248], dtype=float32),
 array([0.        , 0.03648946, 0.        , ..., 0.00997932, 0.02375531,
        0.04649904], dtype=float32),
 array([0.        , 0.03642139, 0.0071044 , ..., 0.00140777, 0.        ,
        0.05435034], dtype=float32),
 array([0.00232171, 0.05030547, 0.00747744, ..., 0.00346683, 0.03391016,
        0.04565726], dtype=float32),
 array([0.00306835, 0.06240455, 0.        , ..., 0.00170629, 0.02032891,
        0.05833263], dtype=float32),
 array([0.        , 0.10469133, 0.00198095, ..., 0.        , 0.0303375 ,
        0.02712859], dtype=float32),
 array([0.        , 0.12438442, 0.01465612, ..., 0.00289708, 0.04055163,
        0.06534591], dtype=float32),
 array([0.        , 0.09169212, 0.01569912, ..., 0.        , 0.00503584,
        0.04560043], dtype=float32),
 array([0.        , 0.09545277, 0.01153318, ..., 0.0007301 , 0.04513262,
        0.07661065], dtype=float32),
 array([0.

In [9]:
pkl.dump(image_features, open('Images_features.pkl','wb'))
# pkl.dump(filenames, open('filenames.pkl','wb'))

In [10]:
pkl.dump(filenames, open('filenames.pkl','wb'))

In [11]:
import pickle as pkl

f = pkl.load(open('filenames.pkl','rb'))
print(type(f))
print(len(f))
print(f[:3])


<class 'list'>
44441
['images\\10000.jpg', 'images\\10001.jpg', 'images\\10002.jpg']
